package com.dubtimes.connect;

import android.content.*;import android.database.Cursor;import android.database.sqlite.*;import java.util.*;

public class AppDb extends SQLiteOpenHelper {
 public static final String DB_NAME="dub_times_connect_android.db";public AppDb(Context c){super(c,DB_NAME,null,2);}
 @Override public void onCreate(SQLiteDatabase db){
  db.execSQL("CREATE TABLE projects(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE COLLATE NOCASE,discord_thread_id TEXT DEFAULT '')");
  db.execSQL("CREATE TABLE students(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE COLLATE NOCASE)");
  db.execSQL("CREATE TABLE characters(id INTEGER PRIMARY KEY AUTOINCREMENT,project_id INTEGER NOT NULL,name TEXT NOT NULL,student_id INTEGER,state TEXT NOT NULL DEFAULT 'Pendiente',collective INTEGER NOT NULL DEFAULT 0,version TEXT DEFAULT 'VERSION 1',suggestion TEXT DEFAULT '',entries INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(project_id) REFERENCES projects(id),FOREIGN KEY(student_id) REFERENCES students(id))");
  db.execSQL("CREATE TABLE character_members(character_id INTEGER NOT NULL,student_id INTEGER NOT NULL,PRIMARY KEY(character_id,student_id))");
  db.execSQL("CREATE TABLE classes(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,project_id INTEGER NOT NULL,character_id INTEGER,number INTEGER NOT NULL,total INTEGER NOT NULL,pending INTEGER NOT NULL DEFAULT 0,paid INTEGER NOT NULL DEFAULT 1,receipt TEXT DEFAULT '',created_at INTEGER NOT NULL)");
 }
 @Override public void onUpgrade(SQLiteDatabase db,int oldV,int newV){if(oldV<2){try{db.execSQL("ALTER TABLE projects ADD COLUMN discord_thread_id TEXT DEFAULT ''");}catch(Exception ignored){}try{db.execSQL("ALTER TABLE characters ADD COLUMN version TEXT DEFAULT 'VERSION 1'");}catch(Exception ignored){}try{db.execSQL("ALTER TABLE characters ADD COLUMN suggestion TEXT DEFAULT ''");}catch(Exception ignored){}try{db.execSQL("ALTER TABLE characters ADD COLUMN entries INTEGER NOT NULL DEFAULT 0");}catch(Exception ignored){}db.execSQL("CREATE TABLE IF NOT EXISTS character_members(character_id INTEGER NOT NULL,student_id INTEGER NOT NULL,PRIMARY KEY(character_id,student_id))");}}
 public long addProject(String n){ContentValues v=new ContentValues();v.put("name",n.trim());return getWritableDatabase().insertOrThrow("projects",null,v);} public long addStudent(String n){ContentValues v=new ContentValues();v.put("name",n.trim());return getWritableDatabase().insertOrThrow("students",null,v);}
 public long addCharacter(long p,String n,Long s,String st,boolean col){ContentValues v=new ContentValues();v.put("project_id",p);v.put("name",n.trim());if(s==null)v.putNull("student_id");else v.put("student_id",s);v.put("state",st);v.put("collective",col?1:0);long id=getWritableDatabase().insert("characters",null,v);if(s!=null)addMember(id,s);return id;}
 void addMember(long cid,long sid){ContentValues v=new ContentValues();v.put("character_id",cid);v.put("student_id",sid);getWritableDatabase().insertWithOnConflict("character_members",null,v,SQLiteDatabase.CONFLICT_IGNORE);}
 public List<Row> projects(){return rows("SELECT id,name,discord_thread_id FROM projects ORDER BY name COLLATE NOCASE",null);} public List<Row> students(){return rows("SELECT id,name FROM students ORDER BY name COLLATE NOCASE",null);}
 public List<Row> studentsForProject(long p){return rows("SELECT DISTINCT s.id,s.name FROM students s WHERE s.id IN (SELECT c.student_id FROM characters c WHERE c.project_id=? AND c.student_id IS NOT NULL UNION SELECT m.student_id FROM character_members m JOIN characters c ON c.id=m.character_id WHERE c.project_id=?) ORDER BY s.name COLLATE NOCASE",new String[]{""+p,""+p});}
 public List<Row> characters(long p){return rows("SELECT c.id,c.name,c.state,c.collective,c.student_id,c.version,c.suggestion,c.entries,COALESCE(s.name,'Sin asignar') student_name FROM characters c LEFT JOIN students s ON s.id=c.student_id WHERE c.project_id=? ORDER BY c.collective,c.name COLLATE NOCASE",new String[]{""+p});}
 public List<Row> charactersForStudent(long p,long s){return rows("SELECT DISTINCT c.id,c.name,c.state,c.collective,c.version FROM characters c LEFT JOIN character_members m ON m.character_id=c.id WHERE c.project_id=? AND (c.student_id=? OR m.student_id=?) ORDER BY c.collective,c.name COLLATE NOCASE",new String[]{""+p,""+s,""+s});}
 public Row latestClass(long p,long s){List<Row> r=rows("SELECT number,total,pending,paid,receipt FROM classes WHERE project_id=? AND student_id=? ORDER BY created_at DESC,id DESC LIMIT 1",new String[]{""+p,""+s});return r.isEmpty()?null:r.get(0);}
 public long addClass(long p,long s,Long c,int n,int t,int pending,boolean paid,String receipt){ContentValues v=new ContentValues();v.put("project_id",p);v.put("student_id",s);if(c==null)v.putNull("character_id");else v.put("character_id",c);v.put("number",n);v.put("total",t);v.put("pending",pending);v.put("paid",paid?1:0);v.put("receipt",receipt==null?"":receipt.trim());v.put("created_at",System.currentTimeMillis());return getWritableDatabase().insert("classes",null,v);}
 long ensureStudent(SQLiteDatabase d,String name){try(Cursor c=d.rawQuery("SELECT id FROM students WHERE name=? COLLATE NOCASE",new String[]{name})){if(c.moveToFirst())return c.getLong(0);}ContentValues v=new ContentValues();v.put("name",name);return d.insertOrThrow("students",null,v);}
 public void replaceProjectsFromDiscord(List<DiscordSync.ProjectData> ps){SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{for(DiscordSync.ProjectData p:ps){long pid;try(Cursor c=d.rawQuery("SELECT id FROM projects WHERE discord_thread_id=? OR name=? COLLATE NOCASE LIMIT 1",new String[]{p.threadId,p.name})){if(c.moveToFirst())pid=c.getLong(0);else{ContentValues v=new ContentValues();v.put("name",p.name);v.put("discord_thread_id",p.threadId);pid=d.insertOrThrow("projects",null,v);}}ContentValues pv=new ContentValues();pv.put("name",p.name);pv.put("discord_thread_id",p.threadId);d.update("projects",pv,"id=?",new String[]{""+pid});d.delete("character_members","character_id IN (SELECT id FROM characters WHERE project_id=?)",new String[]{""+pid});d.delete("characters","project_id=?",new String[]{""+pid});for(DiscordSync.CharacterData c:p.characters){ArrayList<Long> ids=new ArrayList<>();for(String sn:c.students)ids.add(ensureStudent(d,sn));ContentValues v=new ContentValues();v.put("project_id",pid);v.put("name",c.name);v.put("state",c.state);v.put("collective",c.collective?1:0);v.put("version",c.version);v.put("suggestion",c.suggestion);v.put("entries",c.entries);if(ids.size()==1&&!c.collective)v.put("student_id",ids.get(0));else v.putNull("student_id");long cid=d.insertOrThrow("characters",null,v);for(long sid:ids){ContentValues m=new ContentValues();m.put("character_id",cid);m.put("student_id",sid);d.insertWithOnConflict("character_members",null,m,SQLiteDatabase.CONFLICT_IGNORE);}}}d.setTransactionSuccessful();}finally{d.endTransaction();}}
 public String memberNames(long cid){List<Row> r=rows("SELECT s.name FROM students s JOIN character_members m ON m.student_id=s.id WHERE m.character_id=? ORDER BY s.name COLLATE NOCASE",new String[]{""+cid});ArrayList<String> n=new ArrayList<>();for(Row x:r)n.add(x.s("name"));return n.isEmpty()?"Sin asignar":android.text.TextUtils.join(", ",n);}
 private List<Row> rows(String sql,String[] a){ArrayList<Row> o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery(sql,a)){while(c.moveToNext()){Row r=new Row();for(int i=0;i<c.getColumnCount();i++){String n=c.getColumnName(i);if(c.getType(i)==Cursor.FIELD_TYPE_INTEGER)r.put(n,c.getLong(i));else r.put(n,c.getString(i));}o.add(r);}}return o;}
 public static class Row extends HashMap<String,Object>{public long l(String k){Object v=get(k);return v instanceof Number?((Number)v).longValue():0;}public String s(String k){Object v=get(k);return v==null?"":String.valueOf(v);}}
}
