package com.dubtimes.connect;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.content.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
 final int BG=Color.rgb(8,14,24),SURFACE=Color.rgb(14,24,39),CARD=Color.rgb(18,31,49),TEXT=Color.rgb(241,245,249),MUTED=Color.rgb(148,163,184),BORDER=Color.rgb(42,57,78),ACCENT=Color.rgb(112,91,255),GREEN=Color.rgb(72,199,116),YELLOW=Color.rgb(245,183,62),BLUE=Color.rgb(75,148,255),RED=Color.rgb(244,90,90);
 LinearLayout body,bottomNav; int currentTab=0; AppDb db; long projectId=-1,studentId=-1; String project="Sin proyecto",student="Sin estudiante";
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(SURFACE);getWindow().setNavigationBarColor(BG);db=new AppDb(this);restoreSelection();showProjects();}
 void restoreSelection(){List<AppDb.Row> ps=db.projects();if(!ps.isEmpty()){projectId=ps.get(0).l("id");project=ps.get(0).s("name");List<AppDb.Row> ss=db.studentsForProject(projectId);if(!ss.isEmpty()){studentId=ss.get(0).l("id");student=ss.get(0).s("name");}}}
 GradientDrawable shape(int c,float r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp((int)r));return d;} GradientDrawable outlined(int c,float r,int st){GradientDrawable d=shape(c,r);d.setStroke(dp(1),st);return d;}
 TextView tv(String s,int sp,boolean bold,int c){TextView v=new TextView(this);v.setText(s);v.setTextColor(c);v.setTextSize(sp);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setGravity(Gravity.CENTER_VERTICAL);return v;} Space space(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
 TextView section(String s){TextView v=tv(s.toUpperCase(Locale.ROOT),11,true,MUTED);v.setLetterSpacing(.08f);v.setPadding(dp(4),dp(8),0,dp(6));return v;} LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),dp(13),dp(16),dp(13));l.setBackground(outlined(CARD,16,BORDER));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(9));l.setLayoutParams(p);return l;}
 TextView chip(String s,int c){TextView v=tv(s,11,true,c);v.setPadding(dp(9),dp(4),dp(9),dp(4));v.setBackground(outlined(Color.argb(28,Color.red(c),Color.green(c),Color.blue(c)),50,Color.argb(90,Color.red(c),Color.green(c),Color.blue(c))));return v;} Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setAllCaps(false);b.setBackground(shape(ACCENT,14));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(50));p.setMargins(0,dp(5),0,dp(5));b.setLayoutParams(p);return b;} Button secondary(String s){Button b=primary(s);b.setTextColor(TEXT);b.setBackground(outlined(SURFACE,14,BORDER));return b;}
 void base(String h,String sub,int tab){currentTab=tab;LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setPadding(dp(18),dp(13),dp(18),dp(12));top.setBackgroundColor(SURFACE);top.addView(tv(h,20,true,TEXT));if(sub!=null&&!sub.isEmpty()){TextView st=tv(sub,12,false,MUTED);st.setPadding(0,dp(2),0,0);top.addView(st);}root.addView(top);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(12),dp(14),dp(18));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));bottomNav=new LinearLayout(this);bottomNav.setPadding(dp(8),dp(6),dp(8),dp(7));bottomNav.setBackgroundColor(SURFACE);root.addView(bottomNav,new LinearLayout.LayoutParams(-1,dp(64)));addNav("▦","Proyectos",0);addNav("✓","Clases",1);addNav("●","Sesión",2);setContentView(root);}
 void addNav(String i,String l,int x){TextView n=tv(i+"\n"+l,11,x==currentTab,x==currentTab?ACCENT:MUTED);n.setGravity(Gravity.CENTER);n.setLines(2);n.setBackground(x==currentTab?shape(Color.argb(24,112,91,255),12):null);n.setOnClickListener(v->{if(x==0)showProjects();else if(x==1)showClasses();else showSession();});bottomNav.addView(n,new LinearLayout.LayoutParams(0,-1,1));}
 int stateColor(String s){if(s.equalsIgnoreCase("Terminado"))return GREEN;if(s.equalsIgnoreCase("En proceso"))return YELLOW;if(s.equalsIgnoreCase("Correcciones"))return BLUE;if(s.equalsIgnoreCase("Sin asignar"))return RED;return MUTED;}
 void showProjects(){base("Dub Times Connect","Proyectos y alumnos · Discord + caché local",0);body.addView(section("Proyecto activo"));LinearLayout sel=card();LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.addView(tv(project,16,true,TEXT),new LinearLayout.LayoutParams(0,dp(42),1));r.addView(tv("⌄",22,false,MUTED),new LinearLayout.LayoutParams(dp(42),dp(42)));sel.addView(r);sel.setOnClickListener(v->chooseProject());body.addView(sel);
  if(projectId<0){empty("Todavía no hay proyectos. Creá el primero para comenzar.");Button add=primary("＋  Crear proyecto");add.setOnClickListener(v->addProject());body.addView(add);return;}
  LinearLayout hdr=new LinearLayout(this);hdr.setGravity(Gravity.CENTER_VERTICAL);hdr.addView(section("Estudiantes"),new LinearLayout.LayoutParams(0,-2,1));List<AppDb.Row> ss=db.studentsForProject(projectId);hdr.addView(chip(ss.size()+" estudiantes",BLUE));body.addView(hdr);for(AppDb.Row s:ss)addStudentCard(s);
  if(ss.isEmpty())empty("Este proyecto todavía no tiene estudiantes asignados.");Button ac=secondary("＋  Agregar personaje / asignación");ac.setOnClickListener(v->addCharacter());body.addView(ac);Button ap=secondary("＋  Nuevo proyecto");ap.setOnClickListener(v->addProject());body.addView(ap);Button sync=primary("↻   Sincronizar Discord");sync.setOnClickListener(v->syncDiscord());body.addView(sync);}
 void empty(String s){LinearLayout c=card();TextView t=tv(s,13,false,MUTED);t.setPadding(0,dp(5),0,dp(5));c.addView(t);body.addView(c);}
 void addStudentCard(AppDb.Row s){long sid=s.l("id");String name=s.s("name");List<AppDb.Row> chars=db.charactersForStudent(projectId,sid);String role=chars.isEmpty()?"Sin personajes":chars.get(0).s("name")+(chars.size()>1?" · +"+(chars.size()-1):"");String st=chars.isEmpty()?"Pendiente":chars.get(0).s("state");LinearLayout c=card();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(tv(name,16,true,TEXT),new LinearLayout.LayoutParams(0,dp(32),1));top.addView(chip(st,stateColor(st)));c.addView(top);TextView rr=tv(role,13,false,MUTED);rr.setPadding(0,dp(3),0,0);c.addView(rr);c.setOnClickListener(v->{studentId=sid;student=name;detail();});body.addView(c);}
 void chooseProject(){List<AppDb.Row> ps=db.projects();String[] names=new String[ps.size()+1];for(int i=0;i<ps.size();i++)names[i]=ps.get(i).s("name");names[ps.size()]="＋ Crear proyecto";new AlertDialog.Builder(this).setTitle("Elegir proyecto").setItems(names,(d,w)->{if(w==ps.size()){addProject();return;}projectId=ps.get(w).l("id");project=ps.get(w).s("name");studentId=-1;student="Sin estudiante";showProjects();}).show();}
 void addProject(){ask("Nuevo proyecto","Nombre del proyecto",name->{try{projectId=db.addProject(name);project=name.trim();studentId=-1;student="Sin estudiante";showProjects();}catch(Exception e){toast("Ese proyecto ya existe o el nombre no es válido.");}});}
 void addCharacter(){List<AppDb.Row> all=db.students();LinearLayout box=new LinearLayout(this);box.setPadding(dp(22),0,dp(22),0);box.setOrientation(LinearLayout.VERTICAL);EditText charName=input("Nombre del personaje");box.addView(charName);Spinner sp=new Spinner(this);ArrayList<String> labels=new ArrayList<>();labels.add("Sin asignar");for(AppDb.Row s:all)labels.add(s.s("name"));labels.add("＋ Nuevo estudiante");ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels);sp.setAdapter(a);box.addView(sp);Spinner state=new Spinner(this);state.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Pendiente","En proceso","Correcciones","Terminado","Sin asignar"}));box.addView(state);CheckBox collective=new CheckBox(this);collective.setText("Personaje colectivo");collective.setTextColor(Color.rgb(45,55,72));box.addView(collective);
  AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Agregar personaje").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",null).create();dlg.setOnShowListener(x->dlg.getButton(-1).setOnClickListener(v->{String cn=charName.getText().toString().trim();if(cn.isEmpty()){charName.setError("Escribí un nombre");return;}int pos=sp.getSelectedItemPosition();if(pos==labels.size()-1){dlg.dismiss();ask("Nuevo estudiante","Nombre del estudiante",nm->{long sid;try{sid=db.addStudent(nm);}catch(Exception e){List<AppDb.Row> st=db.students();sid=-1;for(AppDb.Row rr:st)if(rr.s("name").equalsIgnoreCase(nm.trim()))sid=rr.l("id");}if(sid>0)db.addCharacter(projectId,cn,sid,state.getSelectedItem().toString(),collective.isChecked());showProjects();});return;}Long sid=pos==0?null:all.get(pos-1).l("id");db.addCharacter(projectId,cn,sid,state.getSelectedItem().toString(),collective.isChecked());dlg.dismiss();showProjects();}));dlg.show();}
 EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(120,130,145));e.setTextColor(Color.rgb(30,38,50));e.setTextSize(16);e.setSingleLine(true);return e;} interface Got{void go(String s);} void ask(String title,String hint,Got g){EditText e=input(hint);e.setPadding(dp(22),dp(8),dp(22),dp(8));AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setView(e).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String s=e.getText().toString().trim();if(s.isEmpty()){e.setError("Este campo es obligatorio");return;}d.dismiss();g.go(s);}));d.show();}
 void detail(){base(student,project,0);List<AppDb.Row> cs=db.charactersForStudent(projectId,studentId);body.addView(section("Personajes asignados"));for(AppDb.Row x:cs){LinearLayout c=card();LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.addView(tv(x.s("name"),17,true,TEXT),new LinearLayout.LayoutParams(0,dp(35),1));r.addView(chip(x.s("state"),stateColor(x.s("state"))));c.addView(r);body.addView(c);}AppDb.Row lc=db.latestClass(projectId,studentId);LinearLayout last=card();last.addView(tv("Última clase registrada",11,true,MUTED));last.addView(tv(lc==null?"Sin clases":lc.l("number")+"/"+lc.l("total"),20,true,TEXT));body.addView(last);Button b=primary("Registrar una clase");b.setOnClickListener(v->showClasses());body.addView(b);}
 void showClasses(){base("Clases y entregas","Registro local preparado para Discord",1);List<AppDb.Row> ss=projectId<0?new ArrayList<>():db.studentsForProject(projectId);if(ss.isEmpty()){empty("Primero asigná un estudiante a un personaje desde Proyectos.");return;}if(studentId<0){studentId=ss.get(0).l("id");student=ss.get(0).s("name");}
  LinearLayout who=card();who.addView(tv(student,17,true,TEXT));who.addView(tv(project,13,false,MUTED));who.setOnClickListener(v->chooseStudentForClasses());body.addView(section("Estudiante"));body.addView(who);AppDb.Row lc=db.latestClass(projectId,studentId);body.addView(section("Última clase registrada"));LinearLayout last=card();last.addView(tv(lc==null?"Sin clases":lc.l("number")+"/"+lc.l("total"),24,true,TEXT));body.addView(last);Button reg=primary("＋  Registrar clase");reg.setOnClickListener(v->registerClass());body.addView(reg);}
 void chooseStudentForClasses(){List<AppDb.Row> ss=db.studentsForProject(projectId);String[] n=new String[ss.size()];for(int i=0;i<n.length;i++)n[i]=ss.get(i).s("name");new AlertDialog.Builder(this).setTitle("Estudiante").setItems(n,(d,w)->{studentId=ss.get(w).l("id");student=ss.get(w).s("name");showClasses();}).show();}
 void registerClass(){List<AppDb.Row> cs=db.charactersForStudent(projectId,studentId);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(22),0,dp(22),0);Spinner ch=new Spinner(this);ArrayList<String> names=new ArrayList<>();for(AppDb.Row r:cs)names.add(r.s("name"));if(names.isEmpty())names.add("Sin personaje");ch.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));box.addView(ch);EditText num=input("Número de clase");num.setInputType(2|4096);box.addView(num);EditText total=input("Total del paquete");total.setInputType(2);box.addView(total);EditText pending=input("Minutos pendientes (opcional)");pending.setInputType(2);box.addView(pending);CheckBox paid=new CheckBox(this);paid.setText("Paquete pagado");paid.setTextColor(Color.rgb(45,55,72));paid.setChecked(true);box.addView(paid);EditText receipt=input("URL del comprobante (opcional)");box.addView(receipt);
  AlertDialog d=new AlertDialog.Builder(this).setTitle("Registrar clase").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{try{int n=Integer.parseInt(num.getText().toString().trim()),t=Integer.parseInt(total.getText().toString().trim()),p=pending.getText().toString().trim().isEmpty()?0:Integer.parseInt(pending.getText().toString().trim());if(!paid.isChecked())n=-Math.abs(n);else n=Math.abs(n);Long cid=cs.isEmpty()?null:cs.get(ch.getSelectedItemPosition()).l("id");db.addClass(projectId,studentId,cid,n,t,p,paid.isChecked(),receipt.getText().toString());d.dismiss();showClasses();}catch(Exception e){toast("Revisá el número de clase y el total del paquete.");}}));d.show();}
 void showSession(){base("Sesión","Seleccioná quiénes están presentes",2);if(projectId<0){empty("Primero creá un proyecto.");return;}List<AppDb.Row> ss=db.studentsForProject(projectId);body.addView(section("Estudiantes presentes"));ArrayList<Long> selected=new ArrayList<>();for(AppDb.Row s:ss){LinearLayout c=card();CheckBox cb=new CheckBox(this);cb.setText(s.s("name"));cb.setTextColor(TEXT);cb.setTextSize(15);long id=s.l("id");cb.setOnCheckedChangeListener((b,on)->{if(on)selected.add(id);else selected.remove(id);});c.addView(cb);body.addView(c);}Button b=primary("Ver qué pueden grabar");b.setOnClickListener(v->recordable(selected));body.addView(b);}
 void recordable(List<Long> selected){base("Qué pueden grabar",project,2);List<AppDb.Row> cs=db.characters(projectId);boolean any=false;for(AppDb.Row c:cs){long sid=c.l("student_id");if(!selected.isEmpty()&&!selected.contains(sid))continue;any=true;LinearLayout x=card();LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);String label=c.s("name")+(c.l("collective")==1?"  ·  Colectivo":"");r.addView(tv(label,16,true,TEXT),new LinearLayout.LayoutParams(0,dp(34),1));r.addView(chip(c.s("state"),stateColor(c.s("state"))));x.addView(r);x.addView(tv(c.l("collective")==1?db.memberNames(c.l("id")):c.s("student_name"),12,false,MUTED));body.addView(x);}if(!any)empty("No hay personajes asignados para la selección actual.");}
 void syncDiscord(){
  android.content.SharedPreferences sp=getSharedPreferences("discord",MODE_PRIVATE);String token=sp.getString("token","");String guild=sp.getString("guild","");String forum=sp.getString("forum","");
  if(token.isEmpty()||guild.isEmpty()||forum.isEmpty()){discordSettings(true);return;}
  final ProgressDialog pd=new ProgressDialog(this);pd.setTitle("Sincronizar Discord");pd.setMessage("Leyendo proyectos, personajes y estudiantes…");pd.setIndeterminate(true);pd.setCancelable(false);pd.show();
  new Thread(()->{try{List<DiscordSync.ProjectData> ps=new DiscordSync(token,guild,forum).downloadProjects();db.replaceProjectsFromDiscord(ps);runOnUiThread(()->{pd.dismiss();restoreSelection();showProjects();toast("Discord sincronizado: "+ps.size()+" proyecto(s).");});}catch(Exception e){runOnUiThread(()->{pd.dismiss();new AlertDialog.Builder(this).setTitle("No se pudo sincronizar").setMessage(e.getMessage()+"\n\nPodés revisar la configuración de Discord.").setNegativeButton("Cerrar",null).setPositiveButton("Configuración",(d,w)->discordSettings(false)).show();});}}).start();
 }
 void discordSettings(boolean syncAfter){
  android.content.SharedPreferences sp=getSharedPreferences("discord",MODE_PRIVATE);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(22),0,dp(22),0);
  EditText token=input("Token del bot");token.setText(sp.getString("token",""));token.setInputType(129);box.addView(token);EditText guild=input("ID del servidor");guild.setText(sp.getString("guild",""));guild.setInputType(2);box.addView(guild);EditText forum=input("ID del foro de proyectos");forum.setText(sp.getString("forum",""));forum.setInputType(2);box.addView(forum);TextView note=tv("Solo para esta prueba privada: el token queda guardado en este teléfono. No compartas esta APK ni el token.",12,false,Color.rgb(80,90,105));note.setPadding(0,dp(10),0,0);box.addView(note);
  AlertDialog d=new AlertDialog.Builder(this).setTitle("Conexión con Discord").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String t=token.getText().toString().trim(),g=guild.getText().toString().trim(),f=forum.getText().toString().trim();if(t.isEmpty()||g.isEmpty()||f.isEmpty()){toast("Completá token, servidor y foro.");return;}sp.edit().putString("token",t).putString("guild",g).putString("forum",f).apply();d.dismiss();if(syncAfter)syncDiscord();}));d.show();
 }

 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
